apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: LoadBalancer
  ports:
  - name: result-svc-port
    port: 5050
    targetPort: result-port
  selector:
    app: result
