apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: LoadBalancer
  ports:
  - name: vote-svc-port
    port: 5000
    targetPort: vote-port
  selector:
    app: vote
