apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker-deplt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: worker
          name: worker-container
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-info
                  key: redis_host
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-info
                  key: password
